### PR TITLE
Handle ignored native events properly.

### PR DESCRIPTION
**Pull request by nnDarshan**
gluster native events that are being ignored by
gluster integration are not handled correctly, this
is causing an exception in event listener. Which in
turn is leading to an `500 internal server error` in
glusterfs events.log

tendrl-bug-id: Tendrl/gluster-integration#433
Signed-off-by: nnDarshan <darshan.n.2024@gmail.com>

### CODE REVIEW

**Comment by nnDarshan** [comment]
@r0h4n @shtripat Please review

**Comment by shtripat** [comment]
is it like it would show `Event Ignored` on UI for ignored ones?

**Comment by nnDarshan** [comment]
> is it like it would show Event Ignored on UI for ignored ones?

@shtripat No, this will be returned to the gluster events api, when it posts to the event-listener webhook.

**Comment by shtripat** [comment]
@nnDarshan ok. Looks fine otherwise.

**Pull request merged**
