### PR TITLE
Add gdeploy-wrapper for performing gluster actions

### PR DESCRIPTION
**Pull request by nnDarshan**
This patch adds gdeploy-wrapper which acts as an interface
between gluster integration and python-gdeploy. Atoms from
gluster integration will perform gluster related CRUD actions
by invoking gdeploy-wrapper which in turn invokes python-
gdeploy

tendrl-bug-id: Tendrl/gluster-integration#167
Signed-off-by: nnDarshan <darshan.n.2024@gmail.com>

### CODE REVIEW

**Comment by nnDarshan** [comment]
@r0h4n @nthomas-redhat @shtripat Please review

**Comment by r0h4n** [comment]
All our gdeploy wrapper code should go into commons (some parts are used by node-agent and some by gluster-integration), let me know what you think

**Comment by nnDarshan** [comment]
@r0h4n The interfaces that the wrapper provides are very different in each case. In case of gdeploy-wrapper in node-agent it provides interfaces for provisioning related actions like package installation, node_setup for gluster, cluster creation and disk provisioning.
However in case of wrapper in gluster-integration the wrapper provides interface for gluster specific actions for gluster volume management.
So, I feel they fine as is. 
@shtripat Please provide your thoughts

**Comment by shtripat** [comment]
Agree @nnDarshan. I feel we should keep as is.

**Pull request merged**
