### PR TITLE
Dont set cluster level profiling flag if volume level flags Unknown

### PR DESCRIPTION
**Pull request by shtripat**
tendrl-bug-id: Tendrl/gluster-integration#636
Bugzilla-id: https://bugzilla.redhat.com/1578333
Signed-off-by: Shubhendu <shtripat@redhat.com>

### CODE REVIEW

**Comment by shtripat** [comment]
we need a fix for https://github.com/Tendrl/ui/issues/959 as well for this PR to work properly.
@gnehapk ^^^

**Comment by shtripat** [comment]
With these changes behaviour would be like below

1. In case `gluster get-state` command returns volume specific profiling information
- in UI the volumes would show profiling enabled or disabled
- User would be able to enable/disable profiling at volume level from UI
- cluster level value for profiling state would be calculated based on individual volume's profiling values (all volumes enabled = cluster enabled, all volumes disabled = cluster enabled, few volumes enabled = cluster mixed)
- cluster level option for enabling/disabling profiling for all the volumes of the cluster and individual volumes in UI would show the values accordingly yes enabled or disabled

2. In case `gluster get-state` command doesnt return volume specific profiling information
- in UI the volumess would show profiling enabled value as `Unknown` (as there is no information available for volumes from get-state)
- User wont be able to enable/disable profiling for individual volumes
- cluster level value for profiling enabled flag would be set as None initially after import cluster in tendrl
- User can enable / disable profiling for all the volumes at cluster level. This would set the flag accordingly for underlying volumes in cluster. But UI wont be able to show the same for individual volumes (as get-state doesnt report the volume specific profiling information). At cluster level profiling flag would be set accordingly once enable / disable executed from UI

@julienlim @nthomas-redhat @r0h4n comments? suggestions?
This is what was discussed earlier but there were small issues with existing code so these fixes required.

**Comment by julienlim** [comment]
@shtripat @nthomas-redhat @r0h4n @shirshendu @gnehapk 

In looking at https://github.com/Tendrl/gluster-integration/pull/637#issuecomment-389205316, it looks overall fine except for the following:

For #1 (In case gluster get-state command returns volume specific profiling information), for the cluster level value for profiling state, if all volumes disabled, wouldn't that be cluster disabled (vs. "all volumes disabled = cluster enabled")?

**Comment by shtripat** [comment]
@julienlim ah thats a mistake. I will correct the comment above. Thanks for pointing it out.

**Comment by julienlim** [comment]
+1 LGTM

**Comment by shtripat** [comment]
Verified. @gnehapk I understand you have verified this with UI changes as well. Can you confirm?

**Comment by gnehapk** [comment]
@shtripat Yes. Corresponding PR for it - https://github.com/Tendrl/ui/pull/960.

**Pull request merged**
