### PR TITLE
Fix package version issue

### PR DESCRIPTION
**Pull request by TimothyAsirJeyasing**
Currently we have to update the version in many places.
This patch provides easy way to update the package version by
using the following machanism.

Updated Makefile to pickup package version from __init__.py file
and add a section called "gitversion" in Mackfile to update
version in spec file based on github.
Updated setup.py file to pickup version from __init__.py file

tendrl-bug-id: Tendrl/gluster_integration#109
Signed-off-by: Timothy Asir J <tjeyasin@redhat.com>

### CODE REVIEW

**Comment by TimothyAsirJeyasing** [comment]
I am able to build the rpm using this changes
@r0h4n , @nthomas-redhat , @shtripat , Please review

**Comment by shtripat** [comment]
Ken Dreyer should also review this I feel.

**Comment by TimothyAsir** [comment]
Sure, I will add him in my next patch update

**Comment by TimothyAsirJeyasing** [comment]
@ktdreyer , @r0h4n , @nthomas-redhat , @shtripat , Please review

**Comment by r0h4n** [comment]
Let me know if this PR is still needed

**Pull request closed without merging**
