### PR TITLE
Remove gstatus dependency

### PR DESCRIPTION
**Pull request by TimothyAsirJeyasing**
tendrl-bugid:  Tendrl/gluster-integration#558
Signed-off-by: Timothy Asir J <tjeyasin@redhat.com>

### CODE REVIEW

**Comment by TimothyAsirJeyasing** [comment]
@r0h4n , @nthomas-redhat , @shtripat , Please review

**Comment by r0h4n** [comment]
@shtripat @TimothyAsirJeyasing yes, remove from requirements file too

**Comment by TimothyAsirJeyasing** [comment]
Done the changes, @r0h4n , @nthomas-redhat , @shtripat

**Comment by shtripat** [comment]
Have you sent commons PR for @nthomas-redhat 's comment https://github.com/Tendrl/gluster-integration/pull/567#pullrequestreview-99259150

**Comment by r0h4n** [comment]
@shtripat  https://github.com/Tendrl/commons/commit/0bf800f4b8f7f49918288da1dbeec983e1e6d657

**Pull request merged**
