### PR TITLE
Changed default volume deleted flag from False to None

### PR DESCRIPTION
**Pull request by GowthamShanmugam**
tendrl-bug-id: Tendrl/gluster-integration#575

Signed-off-by: GowthamShanmugam <gshanmug@redhat.com>

### CODE REVIEW

**Comment by GowthamShanmugam** [comment]
If volume is deleted flag is marked as True then it won't be changed because we are not pushing None value in etcd

**Comment by GowthamShanmugam** [comment]
@shtripat @nthomas-redhat @r0h4n please review

**Comment by GowthamShanmugam** [comment]
I have changed volume_alert_counter object attribute name from warn_count to alert_count so UI changes is required @gnehapk

**Comment by GowthamShanmugam** [comment]
@shtripat @r0h4n @nthomas-redhat please review

**Comment by r0h4n** [comment]
@GowthamShanmugam I am not sure why you are talking about "volume_alert_counter" in this PR

Also, the commits need to be signed. Please ensure that in future

**Comment by GowthamShanmugam** [comment]
ah, sorry i wrongly commented here :)

**Pull request merged**
