### PR TITLE
Added pre and post runs for volume management flows

### PR DESCRIPTION
**Pull request by shtripat**
tendrl-bug-id: https://github.com/Tendrl/gluster_integration/issues/74

Signed-off-by: Shubhendu <shtripat@redhat.com>

### CODE REVIEW

**Comment by shtripat** [comment]
@r0h4n @brainfunked @nthomas-redhat please review

**Comment by shtripat** [comment]
@nnDarshan I may try to create a base class which has the common code to get the volume details from etcd. The parsing logic could be specific to individuals as they are different from each other.

**Comment by shtripat** [comment]
@brainfunked Agree. Also we have come to a stage where during hackthon all the test case coverages gone for way below expected. I would add for the code added here, but we would need separate effort to make sure code comes back to original code coverage level.

**Comment by brainfunked** [comment]
@shtripat Sure, but let's start committing test cases for any code being pushed.

**Comment by shtripat** [comment]
Verified the changes and test cases. Works fine.

**Comment by shtripat** [comment]
@brainfunked @r0h4n @nthomas-redhat @anmolbabu @nnDarshan please review.

**Comment by r0h4n** [comment]
- Correct commit msg
- Provide more details on the bug or file a spec

**Comment by shtripat** [comment]
@r0h4n will explain the detail in bug

**Comment by r0h4n** [comment]
any updates on this?

**Comment by shtripat** [comment]
@r0h4n added details as requested in https://github.com/Tendrl/gluster_integration/issues/74. Will need to rebase this PR and test once more. Will update soon.

**Comment by r0h4n** [comment]
Let me know if this is to be re-opened @shtripat

**Pull request closed without merging**
